Add auto-merge to checks fix

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -23,6 +23,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install flake8
+          
       - name: Run flake8 linter
         run: |
           git fetch origin feature/django-app --depth=1
@@ -46,25 +47,25 @@ jobs:
         run: docker compose build
 
       - name: Run Unit Tests
-        run: docker compose -f docker-compose.yml run --rm app sh -c "python manage.py test"
+        run: docker compose run --rm app sh -c "python manage.py test"
 
   merge_to_dev:
     runs-on: ubuntu-latest
-    needs: [lint, unit_test]
+    needs: [lint, unittest]
     if: ${{ needs.lint.result == 'success' && needs.unittest.result == 'success' }}
+
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Git credentials
         run: |
-          git config --global user.email haider.sde@gmail.com
+          git config --global user.email "haider.sde@gmail.com"
           git config --global user.name "haider"
 
       - name: Get branch name
         id: get_branch
-        run: |
-          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
+        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
 
       - name: Checkout dev branch
         run: |
@@ -93,4 +94,7 @@ jobs:
           PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
         run: |
           git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
-          git push origin dev
+          git push origin dev || {
+            echo "Push failed.";
+            exit 1;
+          }
